app = "tiktok-automation-cortes"
primary_region = "gru"

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[env]
  PORT = "5000"
  FLASK_ENV = "production"

[mounts]
  source = "tiktok_data"
  destination = "/app/src/database"

